config/routes.rb
Rails.application.routes.draw do
  resources :event_models
  resources :models
  resources :designers
  resources :events
  resources :users

  resources :events, only: [:edit] do 
    resources :event_models, only: [:edit, :new, :create]
  end 
  
  
  
  
  
  patch "/sessions/reset", to: "sessions#reset"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/event_model.rb
class EventModel < ApplicationRecord
  belongs_to :model
  belongs_to :event

  def event_models
    EventModel.joins(:events, :users).where(event_models: {event_model_id: self.id})
  end 
  

end

app/controllers/event_models_controller.rb
class EventModelsController < ApplicationController
    def index
        @eventmodels = EventModel.all
        @designers = Designer.all
        @eventmodel = EventModel.new
    end
    
    
    def new 
        @events = Event.all
        @models = Model.all
        @designers = Designer.all
        # @eventmodels = Eventmodel.all
        @eventmodel = EventModel.new 
        # byebug
        @event = Event.find(params[:event_id])
    end 

    def show 
        @eventmodel = EventModel.find(params[:id])
    end

    

    def create
        byebug
        @event = Event.find(params[:event_id])
        # byebug
        # @event.event_models.create(model_id: params[:event_model][:model_id])
        EventModel.create(model_id: params[:event_model][:model_id], event_id: params[:event_id])
    #    @eventmodel =  EventModel.create(params.require(:event_model).permit(:event_id, :model_id))
        # redirect_to user_path(@current_user) 
        redirect_to event_path(@event)
        #event_path(params)
    end

    def edit
        # byebug
        # @eventmodel = EventModel.where(event_id: params[:id])
        @models = Model.all
        @event_id = Event.find(params[:event_id])
        @eventmodel = EventModel.find(params[:id])
        # @eventmodels = EventModel.all
        # @eventmodel = EventModel.find((params.require(:event_model).permit(:event_id, :model_id)))
        # @eventmodel = EventModel.find(params[:id])
    
        # find_event_model_id

        # byebug
        # redirect_to edit_event_model_path
    end

    def update
        
        @eventmodel = EventModel.find(params[:id])
        pat_params = params.require(:event_model).permit(:model_id)
        @eventmodel.update(pat_params)
        redirect_to event_path(@eventmodel.event)
    end

    def destroy 
        @eventmodel = EventModel.find(params[:id])
        @event = Event.find(params[:id])
        @eventmodel.destroy
        redirect_to event_path(@eventmodel.event)
    end 


    private 

    def find_event_model_id
        @eventmodelid = @event.event_models.map do |x|
            x.id
        end 
    end 
            
        
   


end

app/helpers/event_models_helper.rb
module EventModelsHelper
end

app/views/event_models/edit.html.erb
<h1>Hello</h1>

<%= form_for @eventmodel do |f| %>
  <%= f.label :model_id %>
  <%= f.collection_select :model_id, Model.all, :id, :name, prompt: true %>

<%= f.submit %>
<% end %>


<%= button_to 'Dont want this model', event_model_path(@eventmodel), method: :delete %>

<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/event_models/index.html.erb
hi

<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/event_models/new.html.erb
<h1></h1>
<%= form_for [@event, @eventmodel] do |f| %>

  <%= f.label :model %>
    <%= f.collection_select :model_id, @models, :id, :name, prompt: true %>
    <%= f.hidden_field :event_id, value: @event.id  %>
    
<%= f.submit "You got the model" %>

<% end %>



<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>