config/routes.rb
Rails.application.routes.draw do
  resources :event_models
  resources :models
  resources :designers
  resources :events
  resources :users

  resources :events, only: [:edit] do 
    resources :event_models, only: [:edit, :new, :create]
  end 
  
  
  
  
  
  patch "/sessions/reset", to: "sessions#reset"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events
    has_many :designers, through: :events
    has_many :event_models, through: :events

    # validates :name, presence: true
    validates :username, uniqueness: true
    validates :username, presence: true
    validates :password_digest,  presence: true
    
    has_secure_password
    
    def models
        Model.joins(:event_models, :events).where(events: {user_id: self.id})
    end

   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  skip_before_action :authenticated, only: [:new, :create]

def index 
  @users = User.all
end

  def new
    @user = User.new
  end

  def show 
    @user = User.find(params[:id])
    @events = @user.events 
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = ["Invalid Username Or Password"]
      redirect_to new_user_path
    end
  end

  def edit
    @user = @current_user
    
  end

  private

  def user_params
    params.require(:user).permit(:username,:password)
  end
end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.username %>

<% end %>


<hr>


<%= link_to 'View records ', event_path %>

<hr>

<%= link_to 'create event', new_event_path %>



<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/users/new.html.erb
<center>

<div class="container">

<%= render "shared/heading", title: "Welcome" %>

<%= form_for @user, html: { class: "form" } do |f| %>
  <h4 class="form-header">Create account</h4>

  <div class="form-field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="form-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

<div class="form-field">
    <%= f.label :gender %>
    <%= f.text_field :gender%>
  </div>

  <div class="form-field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>


  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li class="error"><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-field">
    <%= f.submit class: "button" %>
  </div>
<% end %>


</div>


</center>


<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/users/show.html.erb
<hr>

<center>

<hr>

<%= button_to 'new event', new_event_path, method: :get %>
<br>
<%= button_to 'Logout', logout_path, method: :delete   %>


<br>

<h1 style="font-size: 27px"><b>Here are your registered events  </b></h1>
<br>

<table class="Events">
  <thead>
    <tr>
      <th>Name (click to edit) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</th>
      <th>Location   .</th>
      <th>Date       &nbsp;   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th>
      <th>Designer name  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;       </th>
      <th>Models</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |x| %>
      <tr>
        <td>
          <%= link_to x.name, event_path(x) %>
        </td>
        <td><%= x.location %></td>
        <td><%= x.date %></td>
        <td><%= x.designer.name %></td>
        <% x.models.each do |m| %>
        <td><%= m.name %><td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>



</center>


<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>