config/routes.rb
Rails.application.routes.draw do
  resources :event_models
  resources :models
  resources :designers
  resources :events
  resources :users

  resources :events, only: [:edit] do 
    resources :event_models, only: [:edit, :new, :create]
  end 
  
  
  
  
  
  patch "/sessions/reset", to: "sessions#reset"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_models, dependent: :destroy
  has_many :models, through: :event_models
  belongs_to :user
  belongs_to :designer

  # Event.joins(:events_models).where(event_models: {model_id: model.id})

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def new
        @event = Event.new
        @designers = Designer.all
        @models = Model.all
        @users = User.all
        
        @event_model_model = @event.models
    end

    def index
        @events = Event.all
        @event_models = EventModel.all
    end

    
    def create
            # pt_params = params.require(:event).permit(:designer_id, :location, :date, :name)
            @event = Event.create(model_params.merge(user_id: @current_user.id))
            # EventModel.create(event_id: @event.id, )
            redirect_to new_event_event_model_path(@event)
    end

    def show
        @event = Event.find(params[:id])
        @event_models = @event.models
        @eventmodels = @event.event_models

        # @model = Model.new
        # byebug
    end 


    def edit
        @event = Event.find(params[:id])
        @eventmodel = @event.event_models

        # byebug
        # @eventmodel = Eventmodel.find(params[:id])
        # @eventmodel = EventModel.new
    #  redirect_to new_event_model_path
    end 

    def update
        # @eventmodel = EventModel.new
        # byebug
        @event = Event.find(params[:id])
        # @eventmodel = Eventmodel.find(params[:id])
        # params.require(:event).permit(:designer_id, :location, :date, :name)
        @event.update(model_params.merge(user_id: @current_user.id))
        # @event_model = @event.eventmodels
        redirect_to user_path(@current_user)
    end 

    def destroy 
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to user_path(@current_user)
    end 

    private

    def model_params
        params.require(:event).permit(:designer_id, :location, :date, :name)
    end 



end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
HI
<h1></h1>
<%= form_for @event do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :date %>
<%= f.date_field :date %>

<%= f.label :location %>
<%= f.text_field :location %>
  

    <%= f.label :designer %>
    <%= f.collection_select :designer_id, Designer.all, :id, :name, prompt: true %>



<%= f.submit "edit Event" %>
<% end %>

<%#= link_to  "Edit model", edit_event_event_model_path(@event ) %>

<% @eventmodel.each do |x| %>
    <%= link_to "Edit #{x.model.name}", "/events/#{@event.id}/event_models/#{x.id}/edit" %>
<% end %>




<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/events/index.html.erb
<% @events.each do |x| %>
  <li><%= link_to x.name ,event_path(x)%>- <%= x.date %>- <%= x.location %> - <%= x.models.name %> --<%= x.designer.name %></li>

<% end %>

<hr>

<% @events.each do |x| %>
  <li><%= link_to x.name%>- <%= x.date %>- <%= x.location %> - <%= x.models.name %> --<%= x.designer.name %></li>
<% end %>

<hr>



<hr>
<li>
<% @event_models.each do |x| %>
  <li><%= x.event.name %><%= x.event.date %>- <%= x.event.location %> - <%= x.model.name %> --<%= x.event.designer.name %></li>

  <%= link_to "edit event model", edit_event_model_path(x)%>
  <%= link_to "edit event designer and details ", edit_event_path(x)%>
  </li>

<% end %>





<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/events/new.html.erb
<h1></h1>
<%= form_for @event do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :date %>
<%= f.date_field :date %>

<%= f.label :location %>
<%= f.text_field :location %>
  

    <%= f.label :designer %>
    <%= f.collection_select :designer_id, Designer.all, :id, :name, prompt: true %>
<%= f.submit "Create Event" %>

<% end %>




<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>

app/views/events/show.html.erb
  <center>
  
  
  <li>Name:<%= @event.name %></li>
  <li>Date: <%= @event.date %></li>
  <li>Designer: <%= @event.designer.name %></li>
<li> Location:<%= @event.location %>
<hr>

<% @eventmodels.each do |x| %>
Click below to edit model <%=  button_to x.model.name, edit_event_event_model_path(@event,x), method: :get%> 
  
<% end %>

<br>





<hr>

<%= button_to 'Add more models', new_event_event_model_path(@event), method: :get%> 


<br>

<%= button_to "Edit THIS event", edit_event_path(@event), method: :get %>

<br>



<%= button_to "Delete event", event_path(@event), method: :delete %>


</center>

<hr>




<style>
 
 body {
  background: rgb(128,128,128);
  font-family: 'Open Sans', sans-serif;
}

</style>